/**
 * Shared email layout: branded shell + CAN-SPAM footer with one-click unsubscribe.
 *
 * Wraps every transactional and nurture email so the footer/branding stay consistent.
 * The unsubscribe URL is generated by src/lib/messaging/email-footer.ts (single source of truth).
 */

import {
  Body,
  Container,
  Head,
  Hr,
  Html,
  Link,
  Preview,
  Section,
  Text,
} from '@react-email/components'
import * as React from 'react'
import { getUnsubscribeUrl } from '@/lib/messaging/email-footer'

export type LayoutProps = {
  preview: string
  leadId: string
  orgId: string
  orgName: string
  children: React.ReactNode
}

export function Layout({ preview, leadId, orgId, orgName, children }: LayoutProps) {
  const unsubscribeUrl = getUnsubscribeUrl(leadId, orgId)

  return (
    <Html lang="en">
      <Head />
      <Preview>{preview}</Preview>
      <Body style={body}>
        <Container style={container}>
          <Section style={brandHeader}>
            <Text style={brandHeaderText}>{orgName}</Text>
          </Section>

          <Section style={content}>{children}</Section>

          <Hr style={divider} />

          <Section style={footer}>
            <Text style={footerText}>
              {orgName}
              <br />
              You received this email because you submitted an inquiry with us.
              <br />
              <Link href={unsubscribeUrl} style={footerLink}>
                Unsubscribe
              </Link>{' '}
              from future emails.
            </Text>
          </Section>
        </Container>
      </Body>
    </Html>
  )
}

// ── styles (inlined for email-client compatibility) ──

const body: React.CSSProperties = {
  backgroundColor: '#f5f5f5',
  fontFamily:
    '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, sans-serif',
  margin: 0,
  padding: '24px 0',
}

const container: React.CSSProperties = {
  backgroundColor: '#ffffff',
  borderRadius: '8px',
  margin: '0 auto',
  maxWidth: '600px',
  padding: '0',
  overflow: 'hidden',
}

const brandHeader: React.CSSProperties = {
  backgroundColor: '#0f172a',
  padding: '20px 32px',
}

const brandHeaderText: React.CSSProperties = {
  color: '#ffffff',
  fontSize: '18px',
  fontWeight: 600,
  margin: 0,
  letterSpacing: '0.02em',
}

const content: React.CSSProperties = {
  padding: '32px',
}

const divider: React.CSSProperties = {
  borderColor: '#e5e7eb',
  margin: '0 32px',
}

const footer: React.CSSProperties = {
  padding: '16px 32px 24px 32px',
}

const footerText: React.CSSProperties = {
  color: '#9ca3af',
  fontSize: '11px',
  lineHeight: 1.5,
  margin: 0,
  textAlign: 'center',
}

const footerLink: React.CSSProperties = {
  color: '#9ca3af',
  textDecoration: 'underline',
}

// Shared text style helpers exported so per-template files don't redefine them.
export const styles = {
  paragraph: {
    color: '#374151',
    fontSize: '15px',
    lineHeight: 1.6,
    margin: '0 0 16px 0',
  } as React.CSSProperties,
  heading: {
    color: '#0f172a',
    fontSize: '22px',
    fontWeight: 600,
    lineHeight: 1.3,
    margin: '0 0 20px 0',
  } as React.CSSProperties,
  primaryButton: {
    backgroundColor: '#0f172a',
    borderRadius: '6px',
    color: '#ffffff',
    display: 'inline-block',
    fontSize: '15px',
    fontWeight: 600,
    padding: '12px 24px',
    textDecoration: 'none',
  } as React.CSSProperties,
  detailRow: {
    color: '#374151',
    fontSize: '14px',
    lineHeight: 1.5,
    margin: '0 0 6px 0',
  } as React.CSSProperties,
  detailLabel: {
    color: '#6b7280',
    fontWeight: 600,
  } as React.CSSProperties,
}
