/**
 * Cal.com webhook handler.
 *
 * Receives BOOKING_CREATED, BOOKING_RESCHEDULED, BOOKING_CANCELLED events.
 * For each:
 *   - Updates lead.status (consultation_scheduled / consultation_completed flow)
 *   - Inserts into appointments table (so the existing reminder sweep handles 24h + 1h reminders)
 *   - Exits all active campaign enrollments
 *   - Inserts a row into events for downstream forwarders + analytics
 *
 * The lead is identified via metadata.lead_id, which is round-tripped from the booking link
 * generated by src/lib/cal/booking-link.ts.
 *
 * Cal.com signature: HMAC-SHA256 of the raw body using the per-org webhook_secret,
 * sent as the `X-Cal-Signature-256` header.
 *
 * Brief reference: Section 2.4.
 */

import { NextRequest, NextResponse } from 'next/server'
import crypto from 'node:crypto'
import * as React from 'react'
import { createServiceClient } from '@/lib/supabase/server'
import { applyRateLimit } from '@/lib/webhooks/verify'
import { RATE_LIMITS } from '@/lib/rate-limit'
import { exitAllCampaigns } from '@/lib/campaigns/enrollments'
import { logger } from '@/lib/logger'
import { sendEmail } from '@/lib/messaging/resend'
import { decryptField } from '@/lib/encryption'
import { renderEmail } from '@/emails/render'
import { BookingConfirmation } from '@/emails/BookingConfirmation'
import { getUnsubscribeHeaders } from '@/lib/messaging/email-footer'

type CalBookingTrigger =
  | 'BOOKING_CREATED'
  | 'BOOKING_RESCHEDULED'
  | 'BOOKING_CANCELLED'

type CalWebhookPayload = {
  triggerEvent: CalBookingTrigger
  payload: {
    type?: string
    title?: string
    startTime?: string
    endTime?: string
    eventTypeId?: number
    uid?: string
    rescheduleUid?: string
    location?: string
    metadata?: Record<string, unknown>
    attendees?: Array<{ name?: string; email?: string; timeZone?: string }>
    organizer?: { email?: string; name?: string }
    cancellationReason?: string
  }
}

export async function POST(request: NextRequest) {
  const rlError = applyRateLimit(request, RATE_LIMITS.webhook)
  if (rlError) return rlError

  const rawBody = await request.text()
  const signature = request.headers.get('x-cal-signature-256')

  let parsed: CalWebhookPayload
  try {
    parsed = JSON.parse(rawBody)
  } catch {
    return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 })
  }

  // metadata.lead_id is set by booking-link.ts when the lead clicks our generated URL.
  const leadId = parsed.payload?.metadata?.lead_id as string | undefined
  if (!leadId) {
    // Booking made directly on Cal.com without our link — we can't attribute it. Return 200 so Cal stops retrying.
    logger.info('Cal webhook received without lead_id metadata', { trigger: parsed.triggerEvent })
    return NextResponse.json({ ok: true, action: 'ignored_no_lead' })
  }

  const supabase = createServiceClient()

  // Resolve the lead's organization to look up the per-org webhook_secret.
  // Also pull the fields we need for the confirmation email so we don't double-fetch.
  const { data: lead } = await supabase
    .from('leads')
    .select('id, organization_id, status, first_name, email, timezone')
    .eq('id', leadId)
    .single()

  if (!lead) {
    return NextResponse.json({ ok: true, action: 'ignored_unknown_lead' })
  }

  // Verify HMAC signature using the per-org Cal webhook secret.
  const { data: cfg } = await supabase
    .from('connector_configs')
    .select('credentials, enabled')
    .eq('organization_id', lead.organization_id)
    .eq('connector_type', 'cal_com')
    .single()

  const { decryptCredentials } = await import('@/lib/connectors/crypto')
  const decryptedCfg = cfg?.credentials ? decryptCredentials(cfg.credentials as Record<string, unknown>) : null
  const webhookSecret = (decryptedCfg as { webhook_secret?: string } | null)?.webhook_secret
  if (!webhookSecret || !cfg?.enabled) {
    return new NextResponse('Cal.com integration not configured', { status: 401 })
  }

  if (!signature || !verifyCalSignature(rawBody, signature, webhookSecret)) {
    return new NextResponse('Invalid Cal.com signature', { status: 401 })
  }

  const trigger = parsed.triggerEvent
  const startTime = parsed.payload.startTime
  const endTime = parsed.payload.endTime
  const calUid = parsed.payload.uid

  switch (trigger) {
    case 'BOOKING_CREATED': {
      // Compute duration
      const durationMinutes = startTime && endTime
        ? Math.round((new Date(endTime).getTime() - new Date(startTime).getTime()) / 60000)
        : 60

      // Insert appointment so the existing reminder sweep picks it up.
      // appointments.reminder_sent_24h / reminder_sent_1h are flipped by src/app/api/appointments/reminders/route.ts
      await supabase.from('appointments').insert({
        organization_id: lead.organization_id,
        lead_id: leadId,
        type: 'consultation',
        status: 'scheduled',
        scheduled_at: startTime,
        duration_minutes: durationMinutes,
        location: parsed.payload.location || null,
        metadata: {
          source: 'cal_com',
          cal_uid: calUid,
          event_type_id: parsed.payload.eventTypeId,
          title: parsed.payload.title,
        },
      })

      // Move lead to consultation_scheduled if it isn't already past that point.
      if (lead.status !== 'consultation_scheduled' && lead.status !== 'consultation_completed') {
        await supabase
          .from('leads')
          .update({
            status: 'consultation_scheduled',
            consultation_date: startTime,
            consultation_type: 'in_person',
          })
          .eq('id', leadId)
      }

      // Exit all active nurture campaigns — booking is the desired outcome.
      await exitAllCampaigns(supabase, leadId, 'Booked consultation via Cal.com').catch(() => {})

      await insertEvent(supabase, lead.organization_id, leadId, 'lead.booking.created', {
        cal_uid: calUid,
        scheduled_at: startTime,
        duration_minutes: durationMinutes,
        event_type_id: parsed.payload.eventTypeId,
      })

      await supabase.from('lead_activities').insert({
        organization_id: lead.organization_id,
        lead_id: leadId,
        activity_type: 'appointment_scheduled',
        title: 'Consultation booked via Cal.com',
        description: parsed.payload.title || 'Consultation',
        metadata: { cal_uid: calUid, scheduled_at: startTime },
      })

      // Send the booking confirmation email (transactional — not gated by marketing consent;
      // CAN-SPAM exempts transactional/relationship emails triggered by the recipient's action).
      if (lead.email && startTime) {
        try {
          const { data: org } = await supabase
            .from('organizations')
            .select('name')
            .eq('id', lead.organization_id)
            .single()
          const orgName = org?.name || 'Your provider'
          const recipientEmail = decryptField(lead.email) || lead.email

          const { html, text } = await renderEmail(
            React.createElement(BookingConfirmation, {
              leadId,
              orgId: lead.organization_id,
              orgName,
              firstName: lead.first_name || 'there',
              consultLabel: parsed.payload.title || 'consultation',
              scheduledAt: startTime,
              timezone: lead.timezone || undefined,
              durationMinutes,
              location: parsed.payload.location || undefined,
            })
          )

          await sendEmail({
            to: recipientEmail,
            subject: `Confirmed: your ${parsed.payload.title || 'consultation'} with ${orgName}`,
            html,
            text,
            replyTo: undefined,
          })

          // Log the outbound message + headers (one-click unsubscribe header pair available
          // via getUnsubscribeHeaders if/when we move to the Resend headers parameter).
          void getUnsubscribeHeaders(leadId, lead.organization_id)
        } catch (err) {
          logger.warn('Failed to send Cal.com booking confirmation email', {
            leadId,
            err: err instanceof Error ? err.message : String(err),
          })
        }
      }

      // Background: refresh the conversation summary so staff see the new booking
      // reflected in the AI summary the next time they open the thread.
      void refreshLatestConversationSummary(supabase, lead.id, lead.organization_id)

      return NextResponse.json({ ok: true, action: 'booking_created' })
    }

    case 'BOOKING_RESCHEDULED': {
      const oldUid = parsed.payload.rescheduleUid
      // Mark old appointment rescheduled
      if (oldUid) {
        await supabase
          .from('appointments')
          .update({ status: 'rescheduled' })
          .eq('lead_id', leadId)
          .filter('metadata->>cal_uid', 'eq', oldUid)
      }

      // Insert new appointment row for the rescheduled time
      const durationMinutes = startTime && endTime
        ? Math.round((new Date(endTime).getTime() - new Date(startTime).getTime()) / 60000)
        : 60

      await supabase.from('appointments').insert({
        organization_id: lead.organization_id,
        lead_id: leadId,
        type: 'consultation',
        status: 'scheduled',
        scheduled_at: startTime,
        duration_minutes: durationMinutes,
        metadata: {
          source: 'cal_com',
          cal_uid: calUid,
          rescheduled_from: oldUid,
        },
      })

      await supabase
        .from('leads')
        .update({ consultation_date: startTime })
        .eq('id', leadId)

      await insertEvent(supabase, lead.organization_id, leadId, 'lead.booking.rescheduled', {
        cal_uid: calUid,
        previous_cal_uid: oldUid,
        scheduled_at: startTime,
      })

      return NextResponse.json({ ok: true, action: 'booking_rescheduled' })
    }

    case 'BOOKING_CANCELLED': {
      if (calUid) {
        await supabase
          .from('appointments')
          .update({
            status: 'canceled',
            canceled_at: new Date().toISOString(),
          })
          .eq('lead_id', leadId)
          .filter('metadata->>cal_uid', 'eq', calUid)
      }

      // Don't auto-revert status — leave it to staff to decide whether to re-nurture.
      await insertEvent(supabase, lead.organization_id, leadId, 'lead.booking.cancelled', {
        cal_uid: calUid,
        reason: parsed.payload.cancellationReason,
      })

      return NextResponse.json({ ok: true, action: 'booking_cancelled' })
    }

    default: {
      // Unknown trigger — accept and no-op
      return NextResponse.json({ ok: true, action: 'ignored_unknown_trigger', trigger })
    }
  }
}

function verifyCalSignature(rawBody: string, signature: string, secret: string): boolean {
  const expected = crypto.createHmac('sha256', secret).update(rawBody).digest('hex')
  // Cal.com sends the bare hex digest in X-Cal-Signature-256 (no "sha256=" prefix).
  const provided = signature.startsWith('sha256=') ? signature.slice(7) : signature
  if (expected.length !== provided.length) return false
  try {
    return crypto.timingSafeEqual(Buffer.from(expected), Buffer.from(provided))
  } catch {
    return false
  }
}

async function insertEvent(
  supabase: ReturnType<typeof createServiceClient>,
  organizationId: string,
  leadId: string,
  eventType: string,
  payload: Record<string, unknown>
): Promise<void> {
  try {
    await supabase.from('events').insert({
      organization_id: organizationId,
      lead_id: leadId,
      event_type: eventType,
      payload,
    })
  } catch {
    // Best-effort — don't fail the webhook on event-log write failure.
  }
}

/**
 * Find the lead's most recent active conversation (any channel) and trigger a summary refresh.
 * Best-effort, fire-and-forget.
 */
async function refreshLatestConversationSummary(
  supabase: ReturnType<typeof createServiceClient>,
  leadId: string,
  organizationId: string
): Promise<void> {
  try {
    const { data: convo } = await supabase
      .from('conversations')
      .select('id')
      .eq('lead_id', leadId)
      .eq('status', 'active')
      .order('last_message_at', { ascending: false, nullsFirst: false })
      .limit(1)
      .single()
    if (!convo) return
    const { summarizeConversation } = await import('@/lib/ai/summarize')
    await summarizeConversation(supabase, {
      conversationId: convo.id as string,
      organizationId,
      leadId,
    })
  } catch {
    // Summary refresh is observability — never block the webhook.
  }
}
